config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcomes/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :informations
  
  root "informations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
  validates :name, presence: true
  # validates :training_date, presence: true
  # validates :rest_heart_rate, presence: true
  validates :training_duration, presence: true
  validates_presence_of :rpe, inclusion: { in: %w(1..10) }, :message => "只能填寫1～10的數字"
  validates :rpe, numericality: { only_integer: true }
  validates :training_duration, numericality: { only_integer: true }



  def get_fatigue(information)
   information.fatigue = information.training_duration * information.rpe
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  def index
    @information = Information.new
    @informations = Information.all
  end

  def create
    @information = Information.new(params_information)


    if @information.save
      @information.get_fatigue(@information)
      flash[:notice] = "成功建立"
      redirect_to root_path
    else
      @informations = Information.all
      flash[:alert] = @information.errors.full_messages.to_sentence
      render :index
    end
      # request.referrer, alert: @information.errors.full_messages.to_sentence
  end

  private

  def params_information
    params.require(:information).permit(:name, :training_date, :rest_heart_rate, :training_duration, :rpe)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/informations/index.html.erb
<div class="col-md-6 col-md-offset-3">
<!-- 
   <%# if @information.errors.any? %>
    <ul>
      <%# @information.errors.full_messages.each do |mas| %>
        <li><%#= mas %></li>
      <%# end %>
    </ul>
  <%# end %> -->

  <h2>Champion's Fatigue management</h2>
  <br>

  <%= form_for @information, url: informations_path do |f| %>
    <div class="form-group">
      <%#= f.collection_select :athlete, Athlete.all, :id, :name, {prompt: "你是誰" }, {class: 'form-control'} %>
    </div>
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :training_date, 'Training Date' %>
      <%= f.date_field :training_date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :rest_heart_rate, "Rest Heart Rate" %>
      <%= f.text_field :rest_heart_rate, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :training_duration %>
      <%= f.text_field :training_duration, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :rpe, "Session RPE" %>
      <%= f.text_area :rpe, placeholder: "1是輕鬆／10是很累", class: 'form-control intro' %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<br>
<br>
<br>
    <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Training Date</th>
            <th scope="col">Rest Heart Rate</th>
            <th scope="col">Training Duration</th>
            <th scope="col">Seesion RPE</th>
            <th scope="col">Fatigue</th>
          </tr>
        </thead>
        <tbody>
          <% @informations.each do |information| %>
            <tr>
              <th scope="row"><%= information.name %></th>
              <td><%= information.training_date %></td>
              <td><%= information.rest_heart_rate %></td>
              <td><%= information.training_duration %></td>
              <td><%= information.rpe %></td>
              <td><%= information.fatigue %></td>
            </tr>
          <% end %>
        </tbody>
    </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JuileJump</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
    <nav class="navbar navbar-inverse">
       <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to  "<span class='glyphicon glyphicon-home'></span> 首頁".html_safe , root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="pull-right text-right nav navbar-nav">
            <li>
              <%= link_to "#"%>
            </li>
            <%#= link_to("<span class= 'glyphicon glyphicon-shopping-cart'></span> Cart".html_safe, cart_path) %>
            <%#= link_to pluralize(current_cart.item_count, 'Cart', cart_path) %>

            <% if current_user %>
              <% if current_user %>
                <li><%= link_to "<span class= 'glyphicon glyphicon-cog'></span> Admin後臺".html_safe, admin_root_path %></li>
              <% end %>
              <li><%#= link_to("<span class= 'glyphicon glyphicon-list-alt'></span> Order".html_safe, orders_path) %></li>
              <li><%= link_to("<span class= 'glyphicon glyphicon-log-out'></span> 登出".html_safe, destroy_user_session_path, method: :delete) %></li>
              <li><%= link_to("<span class= 'glyphicon glyphicon-wrench'></span> 修改密碼".html_safe, edit_user_registration_path) %></li>
            <% else %>
              <li><%= link_to('註冊', new_user_registration_path) %></li>
              <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% if flash[:notice] %>
        <div class="container">
          <div class="row">
            <div class="alert alert-success alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= notice %>
            </div>
          </div>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="container">
          <div class="row">
            <div class="alert alert-danger alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= alert %>
            </div>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>